apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  namespace: kafka

namespace: kafka

secretGenerator:
  - name: kafdrop
    env: config.env
    type: Opaque

resources:
  - service.yaml
  - deployment.yaml