apiVersion: v1
kind: Service
metadata:
  name: testapp-api
  namespace: testapp
  labels:
    app: testapp-api
spec:
  selector:
    app: testapp-api
  ports:
    - name: testapp-api
      targetPort: 8080
      port: 8080
