apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testapp

commonLabels:
  namespace: testapp
  env: local

resources:
- ../../../../manifests/testapp/testapp-api

patchesStrategicMerge:
- hpa.yaml

configMapGenerator:
- name: testapp-api
  namespace: testapp
  envs:
  - config.env

secretGenerator:
- name: testapp-api
  namespace: testapp
  envs:
  - secrets.env
  type: Opaque

images:
-
  name: my.docker.repository.com/testapp/testapp-api
  newTag: "latest"