apiVersion: v1
kind: Service
metadata:
  name: testapp-app
  namespace: testapp
  labels:
    app: testapp-app
spec:
  selector:
    app: testapp-app
  ports:
    - name: testapp-app
      targetPort: 8080
      port: 8080
